Logic to refuse to start if duplicate entries are present for firefix/aurora. Change 'debug' mode to 'parse' mode. Colorized deamon a bit.

diff --git a/profile-sync-daemon b/profile-sync-daemon
--- a/profile-sync-daemon
+++ b/profile-sync-daemon
@@ -1,15 +1,11 @@
 #!/bin/bash
 # By graysky <graysky AT archlinux DOT us>
 # Inspired by some code originally  written by Colin Verot
-
-PSD_VERS="5.06"
-
-### Arrays
-# ProfileArray is transient used to store profile paths parsed from firefox from and aurora
-# DIRArray is a full path corrected for both relative and absolute paths
+export BLD="\e[01m" RED="\e[01;31m" GRN="\e[01;32m" YLW="\e[01;33m" NRM="\e[00m"
+VERS="5.07"
 
 if [[ ! -f /etc/psd.conf ]]; then
-	echo "Cannot find /etc/psd.conf so bailing.  Reinstall package to use profile-sync-daemon."	# nothing to do if there is no conf file
+	echo "Cannot find /etc/psd.conf so bailing.  Reinstall package to use Profile-sync-daemon."	# nothing to do if there is no conf file
 	exit 1
 else
 	. /etc/psd.conf
@@ -38,6 +34,10 @@ root_check() {
 }
 
 set_which() {
+	### Arrays
+	# profileArr is transient used to store profile paths parsed from firefox from and aurora
+	# DIRArr is a full path corrected for both relative and absolute paths
+
 	local user=$1
 	local browser=$2
 
@@ -45,7 +45,7 @@ set_which() {
 	group="$(stat -c %G $homedir)"
 
 	# reset global variables and arrays
-	unset ProfileArray DIRArray
+	unset profileArr DIRArr
 	PSNAME=
 	BACKUP=
 	DIR=
@@ -57,11 +57,11 @@ set_which() {
 
 	case "$browser" in
 		chromium|midori)
-			DIRArray[0]="$homedir/.config/$browser"
+			DIRArr[0]="$homedir/.config/$browser"
 			PSNAME="$browser"
 			;;
 		google-chrome)
-			DIRArray[0]="$homedir/.config/$browser"
+			DIRArr[0]="$homedir/.config/$browser"
 			PSNAME="chrome"
 			;;
 		firefox)
@@ -71,9 +71,9 @@ set_which() {
 				PSNAME="$browser"
 				for profileItem in ${profileArr[@]}; do
 					if [[ $(echo $profileItem | cut -c1) = "/" ]]; then
-						DIRArray[index]="$profileItem"	# path is not relative
+						DIRArr[index]="$profileItem"	# path is not relative
 					else
-						DIRArray[index]="$homedir/.mozilla/firefox/$profileItem"	# we need to append the default path to give a fully qualified path
+						DIRArr[index]="$homedir/.mozilla/firefox/$profileItem"	# we need to append the default path to give a fully qualified path
 					fi
 					index=$index+1
 				done
@@ -87,20 +87,20 @@ set_which() {
 				PSNAME="aurora"
 				for profileItem in ${profileArr[@]}; do
 					if [[ $(echo $profileItem | cut -c1) = "/" ]]; then
-						DIRArray[index]="$profileItem"	# path is not relative
+						DIRArr[index]="$profileItem"	# path is not relative
 					else
-						DIRArray[index]="$homedir/.mozilla/aurora/$profileItem"	# we need to append the default path to give a fully qualified path
+						DIRArr[index]="$homedir/.mozilla/aurora/$profileItem"	# we need to append the default path to give a fully qualified path
 					fi
 					index=$index+1
 				done
 			fi
 			;;
 		opera|opera-next|qupzilla)
-			DIRArray[0]="$homedir/.$browser"
+			DIRArr[0]="$homedir/.$browser"
 			PSNAME="$browser"
 			;;
 		conkeror.mozdev.org)
-			DIRArray[0]="$homedir/.$browser"
+			DIRArr[0]="$homedir/.$browser"
 			PSNAME="xulrunner"
 			;;
 		*)
@@ -109,7 +109,7 @@ set_which() {
 	esac
 }
 
-refuse_to_start() {
+running_check() {
 	# check for browsers running and refuse to start if so
 	# without this cannot guarantee profile integrity
 	local browser user
@@ -117,7 +117,7 @@ refuse_to_start() {
 		for browser in $BROWSERS; do
 			set_which "$user" "$browser"
 			if [[ -n "$PSNAME" ]] && pgrep -u "$user" "$PSNAME" &>/dev/null; then
-				echo "Refusing to start since $browser is running by $user!"
+				echo "Refusing to start; $browser is running by $user!"
 				exit 1
 			else
 				/bin/true
@@ -126,8 +126,38 @@ refuse_to_start() {
 	done
 }
 
+dup_check() {
+	# only for firefox and aurora
+	# the LAST directory in the profile MUST be unique
+	# make sure there are no duplicates in ~/.mozilla/<browser>/profiles.ini
+	local browser user
+	for user in $USERS; do
+		for browser in $BROWSERS; do
+			set_which "$user" "$browser"
+			if [[ "$browser" = "firefox" ]] || [[ "$browser" = "heftig-aurora" ]]; then
+				if [[ -z ${DIRArr[@]} ]]; then
+					/bin/true # nothing to check
+				else
+					# browser is on system so check profiles
+					#
+					# check that the LAST DIRECTORY in the full path is unique
+					unique_count=$(echo ${DIRArr[@]##*/} | sed 's/ /\n/g' | sort | uniq | wc -l)
+					if [[ ${#DIRArr[@]##*/} -eq $unique_count ]]; then
+						/bin/true	# no problems so do nothing
+					else
+						echo -e " ${RED}Error: ${NRM}${BLD}dup profile for ${GRN}$browser${NRM}${BLD} detected. See psd manpage, correct, and try again."${NRM}
+						[[ "$browser" = "heftig-aurora" ]] && browser="${browser##*-}"	# clip of the 'heftig-' to give correct path
+						echo -e " ${BLD}Must have unique last directories in ${YLW}$homedir/.mozilla/$browser/profiles.ini${NRM}${BLD} to use psd."${NRM}
+						exit 1
+					fi
+				fi
+			fi
+		done
+	done
+}
+
 kill_browsers() {
-	# check for browsers running and kill them to safely sync
+	# check for browsers running and kill them to safely sync/unsync
 	# without this cannot guarantee profile integrity
 	local browser user
 	for user in $USERS; do
@@ -146,32 +176,28 @@ kill_browsers() {
 			### Do we need a secondary, more powerful method of killing if the first fails?
 		done
 	done
-	sleep 2s	# pause allowing things to settle on slow machines
 }
 
-debug() {
-	echo -en "profile-sync-daemon      \E[31m::DEBUG MODE::"
-	tput sgr0 
+parse_conf_file() {
+	echo -e "${RED}Profile-sync-daemon v$VERS${NRM}"
 	echo
-	echo "version: $PSD_VERS"
-	echo
-	echo "/etc/psd.conf will make profile-sync-daemon manage the following:"
+	echo -e "${BLD}Psd will manage the following per ${YLW}/etc/psd.conf${BLD} settings${NRM}${BLD}:"${NRM}
 	echo
 	local browser user
 	for user in $USERS; do
 		for browser in $BROWSERS; do
 			set_which "$user" "$browser"
-			for item in ${DIRArray[@]}; do
+			for item in ${DIRArr[@]}; do
 				DIR="$item"
 				BACKUP="$item-backup"
 				[[ "$browser" = "firefox" ]] || [[ "$browser" = "heftig-aurora" ]] && suffix="-${item##*/}" || suffix=
 
 				if [[ -d "$DIR" ]]; then
-					echo "browser:psname  $browser:$PSNAME"
-					echo "owner/group:    $user:$group"
-					echo "sync target:    $DIR"
-					echo "backup target:  $BACKUP"
-					echo "tmpfs dir:      $VOLATILE/$user-$browser$suffix"
+					echo -e "${BLD}browser:psname  $browser:$PSNAME"${NRM}
+					echo -e "${BLD}owner/group:    $user:$group"${NRM}
+					echo -e "${BLD}sync target:    ${YLW}$DIR"${NRM}
+					echo -e "${BLD}backup target:  ${YLW}$BACKUP"${NRM}
+					echo -e "${BLD}tmpfs dir:      ${RED}$VOLATILE/$user-$browser$suffix"${NRM}
 					echo
 				fi
 			done
@@ -179,7 +205,7 @@ debug() {
 	done
 }
 
-check() {
+ungraceful_state_check() {
 	# if the machine was ungracefully shutdown then the backup will be on the filesystem
 	# and the link to tmpfs will be on the filesystem but the contents will be empty
 	# we need to simply remove the link and rotate the backup into place
@@ -189,7 +215,7 @@ check() {
 	for user in $USERS; do
 		for browser in $BROWSERS; do
 			set_which "$user" "$browser"
-			for item in ${DIRArray[@]}; do
+			for item in ${DIRArr[@]}; do
 				DIR="$item"
 				BACKUP="$item-backup"
 				[[ "$browser" = "firefox" ]] || [[ "$browser" = "heftig-aurora" ]] && suffix="-${item##*/}" || suffix=
@@ -205,7 +231,7 @@ check() {
 	done
 }
 
-sync() {
+do_sync() {
 	root_check
 	touch "$DAEMON_FILE"
 
@@ -213,7 +239,7 @@ sync() {
 	for user in $USERS; do
 		for browser in $BROWSERS; do
 			set_which "$user" "$browser"
-			for item in ${DIRArray[@]}; do
+			for item in ${DIRArr[@]}; do
 				DIR="$item"
 				BACKUP="$item-backup"
 				[[ "$browser" = "firefox" ]] || [[ "$browser" = "heftig-aurora" ]] && suffix="-${item##*/}" || suffix=
@@ -242,7 +268,7 @@ sync() {
 	done
 }
 
-unsync() {
+do_unsync() {
 	root_check
 	rm -f "$DAEMON_FILE"
 
@@ -250,7 +276,7 @@ unsync() {
 	for user in $USERS; do
 		for browser in $BROWSERS; do
 			set_which "$user" "$browser"
-			for item in ${DIRArray[@]}; do
+			for item in ${DIRArr[@]}; do
 				DIR="$item"
 				BACKUP="$item-backup"
 				[[ "$browser" = "firefox" ]] || [[ "$browser" = "heftig-aurora" ]] && suffix="-${item##*/}" || suffix=
@@ -270,29 +296,28 @@ unsync() {
 }
 
 case "$1" in
-	debug)
-		debug
+	p|P|Parse|parse|debug)
+		dup_check && parse_conf_file
 		;;
 	sync)
-		[[ ! -f $DAEMON_FILE ]] && refuse_to_start && check 
-		sync
+		[[ ! -f $DAEMON_FILE ]] && dup_check && running_check && ungraceful_state_check
+		do_sync
 		;;
 	resync)
-		[[ -f $DAEMON_FILE ]] && sync
+		[[ -f $DAEMON_FILE ]] && do_sync
 		;;
 	unsync)
-		[[ -f $DAEMON_FILE ]] && sync && kill_browsers && unsync
+		[[ -f $DAEMON_FILE ]] && do_sync && kill_browsers
+		do_unsync
 		;;
 	*) 
-		echo -en "profile-sync-daemon      \E[31m::USAGE::"
-		tput sgr0 
+		echo -e "${RED}Profile-sync-daemon v$VERS${NRM}"
 		echo
-		echo "version: $PSD_VERS"
+		echo -e " ${BLD}$0 ${NRM}${GRN}{parse|sync|unsync}${NRM}"
 		echo
-		echo "$0 {sync|unsync|debug}"
-		echo "  sync) Force a manual sync."
-		echo "unsync) Force a manual unsync."
-		echo " debug) Parse config file to see which profiles will be managed."
+		echo -e " ${BLD}parse)  ${NRM}${GRN}Parse${NRM}${BLD} config file (${NRM}${YLW}/etc/psd.conf${NRM}${BLD}) to see which profiles will be managed."${NRM}
+		echo -e " ${BLD}sync)   Force a manual ${NRM}${GRN}sync${NRM}${BLD}. Must be run as root user and NOT recommended."${NRM}
+		echo -e " ${BLD}unsync) Force a manual ${NRM}${GRN}unsync${NRM}${BLD}. Must be run as root user and NOT recommended."${NRM}
 		;;
 esac
 exit 0
