grep /proc/filesystem for overlay rather than using modprobe

diff --git a/common/profile-sync-daemon.in b/common/profile-sync-daemon.in
--- a/common/profile-sync-daemon.in
+++ b/common/profile-sync-daemon.in
@@ -74,12 +74,12 @@ dep_check() {
 	command -v awk >/dev/null 2>&1 || {
 	echo -e " ${BLD}I require awk but it's not installed. ${RED}Aborting!"${NRM} >&2; exit 1; }
 	if [[ $OLFS -eq 1 ]]; then
-		modprobe overlay &>/dev/null || {
+		grep overlay /proc/filesystem &>/dev/null || {
 		youare=$(logname)
-		echo -e " ${BLD}The overlay module needs to be loaded to use psd in overlayfs mode."${NRM}
-		echo -e " ${BLD}User $youare does not have permission to run: ${BLU}$(which modprobe) overlay${NRM}${BLD}"
-		echo -e " ${BLD}Load it manually and try again or remove the option from ${BLU}$PSDCONF${NRM}${BLD}."${NRM}
-		echo -e " ${BLD}Note that a kernel version >=3.18.0 is required for overlayfs mode. ${RED}Aborting!"${NRM} >&2; exit 1;}
+		echo -e " ${BLD}Depending on your distro, either the ${BLU}overlay${NRM}${BLD} or ${BLU}overlayfs${NRM}${BLD} module needs to be loaded"${NRM}
+		echo -e " ${BLD}to use psd's in overlay mode."${NRM}
+		echo -e " ${BLD}Load it correct module for your distro manually and try again or remove the option"${NRM}
+		echo -e " ${BLD}from ${BLU}$PSDCONF${NRM}${BLD}. ${RED}Aborting!"${NRM} >&2; exit 1;}
 	fi
 }
 
