trigger resync on sleep, fixes #231

diff --git a/common/profile-sync-daemon.in b/common/profile-sync-daemon.in
--- a/common/profile-sync-daemon.in
+++ b/common/profile-sync-daemon.in
@@ -90,7 +90,7 @@ fi
 if [[ -f "$PID_FILE" ]]; then
   if [[ -f "$PSDCONFDIR/.psd.conf" ]]; then
     PSDCONF="$PSDCONFDIR/.psd.conf"
-    unset USE_OVERLAYFS BROWSERS USE_BACKUPS BACKUP_LIMIT
+    unset USE_OVERLAYFS USE_SUSPSYNC BROWSERS USE_BACKUPS BACKUP_LIMIT
     . "$PSDCONF"
     # defining VOLATILE in the config is deprecated since v6.16
     VOLATILE="$XDG_RUNTIME_DIR"
@@ -132,6 +132,16 @@ case "${USE_OVERLAYFS,,}" in
     ;;
   *)
     OLFS=0
+    ;;
+esac
+
+# simple function to determine user intent rather than using a null value
+case "${USE_SUSPSYNC,,}" in
+  y|yes|true|t|on|1|enabled|enable|use)
+    SUSPSYNC=1
+    ;;
+  *)
+    SUSPSYNC=0
     ;;
 esac
 
@@ -190,6 +200,12 @@ dep_check() {
   if ! command -v awk >/dev/null 2>&1; then
     echo -e " ${BLD}I require awk but it's not installed. ${RED}Aborting!${NRM}" >&2
     exit 1
+  fi
+  if ! command -v gdbus >/dev/null 2>&1; then
+    if [[ $SUSPSYNC -eq 1 ]]; then
+      echo -e " ${BLD}I require gdbus but it's not installed. ${RED}Aborting!${NRM}"
+      exit 1
+    fi
   fi
   if [[ $OLFS -eq 1 ]]; then
     [[ $OLFSVER -ge 22 ]] || {
@@ -526,6 +542,7 @@ do_sync() {
       echo "# will be applied the _next_ time psd is activated."
       echo "#"
       echo "USE_OVERLAYFS=\"$USE_OVERLAYFS\""
+      echo "USE_SUSPSYNC=\"$USE_SUSPSYNC\""
       echo "BROWSERS=\"${BROWSERS[*]}\""
       echo "USE_BACKUPS=\"$USE_BACKUPS\""
     } >> "$PSDCONFDIR/.psd.conf"
@@ -608,6 +625,12 @@ parse() {
   else
     echo -e "${BLD} Overlayfs technology is currently ${RED}inactive${NRM}${BLD}.${NRM}"
   fi
+  psd_suspend_sync_state=$(pgrep -cf "psd-suspend-sync")
+  if [[ "$psd_suspend_sync_state" != 0 ]]; then
+    echo -e "${BLD} Sync on sleep protection is currently ${GRN}active${NRM}${BLD}.${NRM}"
+  else
+    echo -e "${BLD} Sync on sleep protection is currently ${RED}inactive${NRM}${BLD}.${NRM}"
+  fi
   echo
   echo -e "${BLD}Psd will manage the following per ${BLU}${PSDCONF}${NRM}${BLD}:${NRM}"
   echo
@@ -681,6 +704,22 @@ parse() {
   done
 }
 
+take_inhibit_lock() {
+  # ensure we only take one lock at a time
+  release_inhibit_lock
+  # background this to avoid hanging on startup
+  systemd-inhibit \
+    --mode="delay" \
+    --what="sleep" \
+    --who="profile-sync-daemon" \
+    --why="psd resync on suspend" \
+    /usr/bin/psd-suspend-sync &
+}
+
+release_inhibit_lock() {
+  [[ "$(pgrep -cf "psd-suspend-sync")" != 0 ]] && pkill -f psd-suspend-sync
+}
+
 case "$1" in
   p|P|Parse|parse|Preview|preview|debug)
     dep_check
@@ -699,14 +738,25 @@ case "$1" in
     ;;
   startup)
     # target for psd.service's ExecStart= for consistent error handling
+    # also handles taking initial inhibit-lock
     if [[ ! -f $PID_FILE ]]; then
       dep_check
       config_check
       dup_check
       running_check
       ungraceful_state_check
+      [[ $SUSPSYNC -eq 1 ]] && take_inhibit_lock
       echo -e "${BLD}psd startup check successful${NRM}"
     fi
+    ;;
+    suspend-sync)
+      # system preparing for sleep mode, resync when psd is active
+      psd_state=$(systemctl --user is-active psd)
+      [[ "$psd_state" = "active" ]] && do_sync
+      ;;
+  recycle-inhibit-lock)
+    # take inhibit lock for next suspend cycle
+    take_inhibit_lock
     ;;
   sync|resync)
     if [[ -f $PID_FILE ]]; then
@@ -726,6 +776,7 @@ case "$1" in
       do_sync
       kill_browsers
       do_unsync
+      [[ $SUSPSYNC -eq 1 ]] && release_inhibit_lock
     fi
     ;;
   *)
