smarter overlayfs module support

diff --git a/common/profile-sync-daemon.in b/common/profile-sync-daemon.in
--- a/common/profile-sync-daemon.in
+++ b/common/profile-sync-daemon.in
@@ -18,10 +18,10 @@ XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
 PSDCONFDIR="$XDG_CONFIG_HOME/psd"
 PSDCONF="$PSDCONFDIR/psd.conf"
 PID_FILE="$PSDCONFDIR/.$user@$(hostname).pid"
-DOCDIR="/usr/share/doc/psd"
+SHAREDIR="/usr/share/psd"
 
-if [[ ! -d "$DOCDIR" ]]; then
-	echo -e " Missing ${BLU}$DOCDIR${NRM}${BLD} - reinstall the package to use profile-sync-daemon."
+if [[ ! -d "$SHAREDIR" ]]; then
+	echo -e " Missing ${BLU}$SHAREDIR${NRM}${BLD} - reinstall the package to use profile-sync-daemon."
 	exit 1
 fi
 
@@ -39,8 +39,8 @@ elif [[ -d "$HOME/.psd" ]]; then
 	[[ -f "$PSDCONF" ]] && . $PSDCONF
 else
 	mkdir -p "$PSDCONFDIR"
-	if [[ -f "$DOCDIR/psd.conf" ]]; then
-		cp "$DOCDIR/psd.conf" "$PSDCONFDIR"
+	if [[ -f "$SHAREDIR/psd.conf" ]]; then
+		cp "$SHAREDIR/psd.conf" "$PSDCONFDIR"
 		echo -e " First time running psd so please edit ${BLU}$PSDCONF${NRM}${BLD} to your liking and run again."${NRM}
 		exit 0
 	fi
@@ -61,7 +61,7 @@ if [[ -f "$PID_FILE" ]]; then
 fi
 
 # all supported browsers
-ALL_BROWSERS=( $(ls "${DOCDIR}/browsers/") )
+ALL_BROWSERS=( $(ls "${SHAREDIR}/browsers/") )
 BROWSERS=${BROWSERS:-"${ALL_BROWSERS[@]}"}
 
 # prefer using $XDG_RUNTIME_DIR for VOLATILE but fall-back to config value
@@ -94,25 +94,23 @@ case "${USE_BACKUPS,,}" in
 esac
 
 # determine is we are using overlayfs (v22 and below) or overlay (v23 and above)
-# overlay FS v23 and later requires both an upper and a work directory, both on
-# the same filesystem, but not part of the same subtree.
-#
-# ubuntu 15.04 has both overlay and overlayfs so prefer version 23
+# since mount should call modprobe on invocation, check to see if either
+# module is in the tree using modinfo
 
 if [[ $OLFS -eq 1 ]]; then
-	# first test if either module is manually loaded manually or hardcoded
+	# first check to see if either is hardcoded into the kernel
+	# and of course prefer version 23
 	[[ $(grep -ciE "overlayfs$" /proc/filesystems) -eq 1 ]] && OLFSVER=22
 	[[ $(grep -ciE "overlay$" /proc/filesystems) -eq 1 ]] && OLFSVER=23
+fi
 
-	if [[ -z $OLFSVER ]]; then
-		# since mount should call modprobe on invocation, check to see if either
-		# module is in the tree using modinfo
-		modinfo overlayfs &>/dev/null
-		[[ $? -eq 0 ]] && OLFSVER=22
+if [[ -z $OLFSVER ]]; then
+	# if neither is hardcoded, see if either module is available
+	modinfo overlayfs &>/dev/null
+	[[ $? -eq 0 ]] && OLFSVER=22
 
-		modinfo overlay &>/dev/null
-		[[ $? -eq 0 ]] && OLFSVER=23
-	fi
+	modinfo overlay &>/dev/null
+	[[ $? -eq 0 ]] && OLFSVER=23
 fi
 
 # get distro name
@@ -182,7 +180,7 @@ config_check() {
 	fi
 
 	for browser in $(echo "$BROWSERS"); do
-		if [[ ! -f "$DOCDIR/browsers/$browser" ]]; then
+		if [[ ! -f "$SHAREDIR/browsers/$browser" ]]; then
 			# user defined an invalid browser
 			echo -e " ${BLD}${RED}$browser${NRM}${BLD} is not a supported browser. Check config file for typos: ${NRM}${BLU}$PSDCONF"${NRM}
 			exit 1
@@ -254,7 +252,7 @@ load_env_for() {
 	unset DIRArr
 
 	unset PSNAME
-	. "$DOCDIR/browsers/$browser"
+	. "$SHAREDIR/browsers/$browser"
 }
 
 running_check() {
@@ -274,7 +272,7 @@ running_check() {
 suffix_needed(){
 	browser=$1
 	unset check_suffix
-	. "$DOCDIR/browsers/$browser"
+	. "$SHAREDIR/browsers/$browser"
 	[[ -n "$check_suffix" ]]
 }
 
