fixes #253

diff --git a/common/profile-sync-daemon.in b/common/profile-sync-daemon.in
--- a/common/profile-sync-daemon.in
+++ b/common/profile-sync-daemon.in
@@ -187,8 +187,13 @@ dep_check() {
   # checks for dependencies and that psd.conf is setup correctly
   command -v rsync >/dev/null 2>&1 || {
   echo -e " ${BLD}I require rsync but it's not installed. ${RED}Aborting!${NRM}" >&2; exit 1; }
-  command -v modinfo >/dev/null 2>&1 || {
-  echo -e " ${BLD}I require modinfo but it's not installed. ${RED}Aborting!${NRM}" >&2; exit 1; }
+  # https://github.com/graysky2/profile-sync-daemon/issues/253
+  if ! command -v modinfo >/dev/null 2>&1; then
+    if ! command -v /sbin/modinfo >/dev/null 2>&1; then
+      echo -e " ${BLD}I require modinfo but it's not installed. ${RED}Aborting!${NRM}" >&2
+      exit 1
+    fi
+  fi
   command -v awk >/dev/null 2>&1 || {
   echo -e " ${BLD}I require awk but it's not installed. ${RED}Aborting!${NRM}" >&2; exit 1; }
   if [[ $OLFS -eq 1 ]]; then
