do not run as root

diff --git a/common/profile-sync-daemon.in b/common/profile-sync-daemon.in
--- a/common/profile-sync-daemon.in
+++ b/common/profile-sync-daemon.in
@@ -23,12 +23,17 @@ PSDCONF="$PSDCONFDIR/psd.conf"
 SHAREDIR="/usr/share/psd"
 
 if [[ ! -d "$SHAREDIR" ]]; then
-	echo -e " Missing ${BLU}$SHAREDIR${NRM}${BLD} - reinstall the package to use profile-sync-daemon."${NRM}
+	echo -e " ${RED}ERROR:${NRM}${BLD} Missing ${BLU}$SHAREDIR${NRM}${BLD} - reinstall the package to use profile-sync-daemon."${NRM}
+	exit 1
+fi
+
+if [[ $EUID -eq 0 ]]; then
+	echo -e " ${RED}WARNING:${NRM}${BLD} Do not call ${BLU}$0${NRM}${BLD} as root."${NRM}
 	exit 1
 fi
 
 if [[ ! -d "$XDG_RUNTIME_DIR" ]]; then
-	echo -e " Cannot find XDG_RUNTME_DIR which should be set by systemd."
+	echo -e " ${RED}ERROR:${NRM}${BLD} Cannot find XDG_RUNTIME_DIR which should be set by systemd."${NRM}
 	exit 1
 fi
 
