fixed debian scriptlets

diff --git a/common/debian/postinst b/common/debian/postinst
--- a/common/debian/postinst
+++ b/common/debian/postinst
@@ -1,20 +1,53 @@
 #!/bin/sh
 set -e
-sed -i 's/#DAEMON_FILE="\/run\/psd"/DAEMON_FILE="\/var\/run\/psd"/' /etc/psd.conf
-if [ $(grep -c -i debian /etc/issue) = 1 ]; then
-	# debian does not mount /tmp to tmpfs by default so use /dev/shm
-	sed -i 's/#VOLATILE="\/tmp"/VOLATILE="\/dev\/shm"/' /etc/psd.conf
-fi
 
-if [ $(grep -c -i ubuntu /etc/issue) = 1 ]; then
-	# ubuntu does not mount /tmp to tmpfs by default so use /run/shm
-	sed -i 's/#VOLATILE="\/tmp"/VOLATILE="\/run\/shm"/' /etc/psd.conf
-fi
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+#
 
-echo '--------------------------------------------------------------------------'
-echo '  Define which users will make use of the sync in /etc/psd.conf'
-echo '  Read the manpage before use or see the wiki page'
-echo '  https://wiki.archlinux.org/index.php/Profile-sync-daemon'
-echo
-echo '  ALWAYS backup your profiles data before using utils like psd!'
-echo '--------------------------------------------------------------------------'
+case "$1" in
+	configure)
+		[ -f /etc/psd.conf ] && . /etc/psd.conf
+		if [ -z "$USERS" ]; then
+			# empty var means fresh install or user did not setup
+			sed -i 's/#DAEMON_FILE="\/run\/psd"/DAEMON_FILE="\/var\/run\/psd"/' /etc/psd.conf
+			if [ $(grep -c -i debian /etc/issue) = 1 ]; then
+				# debian does not mount /tmp to tmpfs by default so use /dev/shm
+				sed -i 's/#VOLATILE="\/tmp"/VOLATILE="\/dev\/shm"/' /etc/psd.conf
+			fi
+
+			if [ $(grep -c -i ubuntu /etc/issue) = 1 ]; then
+				# ubuntu does not mount /tmp to tmpfs by default so use /run/shm
+				sed -i 's/#VOLATILE="\/tmp"/VOLATILE="\/run\/shm"/' /etc/psd.conf
+			fi
+
+			echo '--------------------------------------------------------------------------'
+			echo '  Define which users will make use of the sync in /etc/psd.conf'
+			echo '  Read the manpage before use or see the wiki page'
+			echo '  https://wiki.archlinux.org/index.php/Profile-sync-daemon'
+			echo
+			echo '  ALWAYS backup your profiles data before using utils like psd!'
+			echo '--------------------------------------------------------------------------'
+		else
+			# no need to process or inform since user is running the pacakge
+			/bin/true
+		fi
+		;;
+	abort-upgrade|abort-remove|abort-deconfigure)
+		/bin/true
+		;;
+	*)
+		echo "postinst called with unknown argument \`$1'" >&2
+		exit 1
+		;;
+esac
+
+exit 0
